import '../models/surah.dart';

class QuranData {
  static List<Surah> getSurahs() {
    return [
      Surah(
        number: 1,
        name: 'الفاتحة',
        englishName: 'Al-Fatihah',
        englishNameTranslation: 'The Opening',
        numberOfAyahs: 7,
        revelationType: 'Meccan',
      ),
      Surah(
        number: 2,
        name: 'البقرة',
        englishName: 'Al-Baqarah',
        englishNameTranslation: 'The Cow',
        numberOfAyahs: 286,
        revelationType: 'Medinan',
      ),
      Surah(
        number: 3,
        name: 'آل عمران',
        englishName: 'Ali \'Imran',
        englishNameTranslation: 'Family of Imran',
        numberOfAyahs: 200,
        revelationType: 'Medinan',
      ),
      Surah(
        number: 4,
        name: 'النساء',
        englishName: 'An-Nisa',
        englishNameTranslation: 'The Women',
        numberOfAyahs: 176,
        revelationType: 'Medinan',
      ),
      Surah(
        number: 5,
        name: 'المائدة',
        englishName: 'Al-Ma\'idah',
        englishNameTranslation: 'The Table Spread',
        numberOfAyahs: 120,
        revelationType: 'Medinan',
      ),
      Surah(
        number: 6,
        name: 'الأنعام',
        englishName: 'Al-An\'am',
        englishNameTranslation: 'The Cattle',
        numberOfAyahs: 165,
        revelationType: 'Meccan',
      ),
      Surah(
        number: 7,
        name: 'الأعراف',
        englishName: 'Al-A\'raf',
        englishNameTranslation: 'The Heights',
        numberOfAyahs: 206,
        revelationType: 'Meccan',
      ),
      Surah(
        number: 8,
        name: 'الأنفال',
        englishName: 'Al-Anfal',
        englishNameTranslation: 'The Spoils of War',
        numberOfAyahs: 75,
        revelationType: 'Medinan',
      ),
      Surah(
        number: 9,
        name: 'التوبة',
        englishName: 'At-Tawbah',
        englishNameTranslation: 'The Repentance',
        numberOfAyahs: 129,
        revelationType: 'Medinan',
      ),
      Surah(
        number: 10,
        name: 'يونس',
        englishName: 'Yunus',
        englishNameTranslation: 'Jonah',
        numberOfAyahs: 109,
        revelationType: 'Meccan',
      ),
      Surah(
        number: 67,
        name: 'الملك',
        englishName: 'Al-Mulk',
        englishNameTranslation: 'The Sovereignty',
        numberOfAyahs: 30,
        revelationType: 'Meccan',
      ),
      Surah(
        number: 112,
        name: 'الإخلاص',
        englishName: 'Al-Ikhlas',
        englishNameTranslation: 'The Sincerity',
        numberOfAyahs: 4,
        revelationType: 'Meccan',
      ),
      Surah(
        number: 113,
        name: 'الفلق',
        englishName: 'Al-Falaq',
        englishNameTranslation: 'The Daybreak',
        numberOfAyahs: 5,
        revelationType: 'Meccan',
      ),
      Surah(
        number: 114,
        name: 'الناس',
        englishName: 'An-Nas',
        englishNameTranslation: 'Mankind',
        numberOfAyahs: 6,
        revelationType: 'Meccan',
      ),
    ];
  }

  static Map<int, List<Ayah>> getAyahs() {
    return {
      1: [
        Ayah(
            number: 1,
            text: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
            numberInSurah: 1,
            juz: 1,
            manzil: 1,
            page: 1,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 2,
            text: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
            numberInSurah: 2,
            juz: 1,
            manzil: 1,
            page: 1,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 3,
            text: 'الرَّحْمَٰنِ الرَّحِيمِ',
            numberInSurah: 3,
            juz: 1,
            manzil: 1,
            page: 1,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 4,
            text: 'مَالِكِ يَوْمِ الدِّينِ',
            numberInSurah: 4,
            juz: 1,
            manzil: 1,
            page: 1,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 5,
            text: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
            numberInSurah: 5,
            juz: 1,
            manzil: 1,
            page: 1,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 6,
            text: 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ',
            numberInSurah: 6,
            juz: 1,
            manzil: 1,
            page: 1,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 7,
            text:
                'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
            numberInSurah: 7,
            juz: 1,
            manzil: 1,
            page: 1,
            ruku: 1,
            hizbQuarter: 1),
      ],
      112: [
        Ayah(
            number: 1,
            text: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
            numberInSurah: 1,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 2,
            text: 'قُلْ هُوَ اللَّهُ أَحَدٌ',
            numberInSurah: 2,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 3,
            text: 'اللَّهُ الصَّمَدُ',
            numberInSurah: 3,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 4,
            text: 'لَمْ يَلِدْ وَلَمْ يُولَدْ',
            numberInSurah: 4,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 5,
            text: 'وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
            numberInSurah: 5,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
      ],
      113: [
        Ayah(
            number: 1,
            text: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
            numberInSurah: 1,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 2,
            text: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ',
            numberInSurah: 2,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 3,
            text: 'مِن شَرِّ مَا خَلَقَ',
            numberInSurah: 3,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 4,
            text: 'وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ',
            numberInSurah: 4,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 5,
            text: 'وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ',
            numberInSurah: 5,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 6,
            text: 'وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
            numberInSurah: 6,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
      ],
      114: [
        Ayah(
            number: 1,
            text: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
            numberInSurah: 1,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 2,
            text: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ',
            numberInSurah: 2,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 3,
            text: 'مَلِكِ النَّاسِ',
            numberInSurah: 3,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 4,
            text: 'إِلَٰهِ النَّاسِ',
            numberInSurah: 4,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 5,
            text: 'مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ',
            numberInSurah: 5,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 6,
            text: 'الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ',
            numberInSurah: 6,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
        Ayah(
            number: 7,
            text: 'مِنَ الْجِنَّةِ وَالنَّاسِ',
            numberInSurah: 7,
            juz: 30,
            manzil: 7,
            page: 604,
            ruku: 1,
            hizbQuarter: 1),
      ],
    };
  }
}
